services:
  backend:
    build:
      context: ./backend
    image: backend:1.0
    container_name: week4-backend
    env_file: .env
    environment:
      GEMINI_API_KEY: /run/secrets/gemini_api_key
    secrets:
      - gemini_api_key
    ports:
      - "8001:8001"
    networks:
      - app-net
    volumes:
      - ./backend/data/:/app/data:ro
    restart: unless-stopped
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
    image: frontend:1.0
    container_name: week4-frontend
    environment:
      BACKEND_URL: /run/secrets/backend_url
    secrets:
      - backend_url
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-net
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: week4-ollama
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_MODEL_PATH:-/usr/share/ollama}/.ollama:/root/.ollama
    networks:
      - app-net
    restart: unless-stopped


networks:
  app-net:
    driver: bridge


secrets:
  gemini_api_key:
    file: secrets/gemini_api_key.txt
  backend_url:
    file: secrets/backend_url.txt
